branches:
  only:
  - master

skip_branch_with_pr: true


platform:
  - x86
  # - x64

configuration:
  - Debug
  # - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  access_token:
    secure: JoKQ6wDekwtEk9su/zJWT12TtHMsHAacSLnPe47/SV22BAfVSMMR8VCyDF/W9bE2
  matrix:
    # - GSL_CXX_STANDARD: 14
    - GSL_CXX_STANDARD: 17

matrix:
    exclude:
    - image: Visual Studio 2015
      GSL_CXX_STANDARD: 17

cache:
  - C:\cmake-3.8.0-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
before_build:
  - ps: |
      cd
      mkdir build
      cd build
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          $env:generator="Visual Studio 14 2015"
      } else {
          $env:generator="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      cmake .. -G "$env:generator" -DGSL_CXX_STANDARD="$env:GSL_CXX_STANDARD" -DGSL_ASM_FOLDER="$($env:APPVEYOR_BUILD_WORKER_IMAGE)_$($env:GSL_CXX_STANDARD)_$($env:PLATFORM)_$($env:CONFIGURATION)"
build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal
# after_build:
#   - cmd: |
#       cd %APPVEYOR_BUILD_FOLDER%
#       asm_helper.cmd

test_script:
  - ctest -j2

artifacts:
  - path: asm
    name: Asm
    type: zip

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "dadonenf@microsoft.com"
  - git config --global user.name "Daniel Donenfeld"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% 
  - git add "asm\%APPVEYOR_BUILD_WORKER_IMAGE%_%GSL_CXX_STANDARD%_%PLATFORM%_%CONFIGURATION%"
  - git commit -m "[skip ci] Update ASM for %APPVEYOR_BUILD_WORKER_IMAGE%_%GSL_CXX_STANDARD%_%PLATFORM%_%CONFIGURATION%"
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git push

deploy: off